name: CD – Trigger Deployment

# ────────────────────────────────────────────────────────────────────────────────
# Grant the token the scopes required by the reusable workflow:
permissions:
  contents: read      # default minimal scope to fetch code
  id-token: write     # allow OIDC tokens for Azure login
  packages: write     # allow writing to GitHub Packages

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g. prod)'
        required: true
        type: environment
      commit_sha:
        description: 'Optional commit SHA to deploy'
        required: false
        default: ''

jobs:
  # 1️⃣ Prepare deployment parameters
  prepare:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.params.outputs.TARGET_ENV }}
      git_ref:    ${{ steps.params.outputs.GIT_REF }}
    steps:
      - name: Determine deployment parameters
        id: params
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "TARGET_ENV=dev" >>"$GITHUB_OUTPUT"
            echo "GIT_REF=${{ github.ref }}" >>"$GITHUB_OUTPUT"
          else
            echo "TARGET_ENV=${{ github.event.inputs.environment }}" >>"$GITHUB_OUTPUT"
            GIT_REF="${{ github.event.inputs.commit_sha }}"
            [[ -z "$GIT_REF" ]] && GIT_REF="${{ github.ref }}"
            echo "GIT_REF=$GIT_REF" >>"$GITHUB_OUTPUT"
          fi

  # 2️⃣ Invoke the reusable deployment workflow
  deploy:
    needs: prepare
    uses: ./.github/workflows/cd-deploy.yml
    with:
      environment:          ${{ needs.prepare.outputs.target_env }}
      tf_vars_file:         ${{ vars.TF_VARS_FILE }}
      project_prefix:       ${{ vars.PROJECT_PREFIX }}
      resource_group_name:  ${{ vars.RESOURCE_GROUP_NAME }}
      run_canary:           ${{ vars.RUN_CANARY == 'true' }}
      git_ref:              ${{ needs.prepare.outputs.git_ref }}
    secrets: inherit
